import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "katex/dist/katex.min.css";
import "./globals.css";

const monstserrat = Montserrat({ subsets: ["latin"], weight: "variable" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children,
	modal
}: Readonly<{
	children: React.ReactNode;
	modal: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${monstserrat.className} antialiased p-5`}>
				{children}
				{modal}
			</body>
		</html>
	);
}
